### ISSUE TITLE
Conflicting types for initDirWindowHeight

### ISSUE THREAD

**Issue by ssuukk** [doj/dracopy#1]
Have you thought about releasing binaries? I hvae a problem while compiling newest source in src/ops.c(53):

Conflicting types for 'initDirWindowHeight'

**Comment by doj** [comment]
I assume that your version of cc65 doesn't like an empty parameter list and requires a "func(void)" declaration. I've just submitted a change to fix that function.
The latest HEAD revision of cc65 doesn't have that problem.

**Comment by doj** [comment]
A link to download compiled binaries is listed on the README.md file.
