### ISSUE TITLE
Format shortcut not working

### ISSUE THREAD

**Issue by 8bit-Dude** [doj/dracopy#5]
Hey, thanks for your continued work on this. I just wanted to report that on latest version *dracopy-1.0doj.zip*, pressing "f" for format does not work. It goes into "DOS command" window instead.

**Comment by doj** [comment]
that is correct, format (and make directory) are just shortcuts for the DOS command window. They simply pre-fill the command with "n:" or "md:".
I have however changed the screen texts now so it's less confusing.
